import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
df=pd.read_csv("results.csv",sep=";")
plt.close()
plt.plot(df["Fraction"],df['PC'])
plt.ylabel("Pair completeness")
plt.xlabel("Fraction of comparisons")
plt.show()
plt.plot(df["Fraction"],df['PQ'])
plt.ylabel("Pair quality")
plt.xlabel("Fraction of comparisons")
plt.show()
plt.plot(df["Fraction"],df['F1Star'])
plt.ylabel("F1*")
plt.xlabel("Fraction of comparisons")
plt.show()
plt.plot(df["Fraction"],df['F1'])
plt.ylabel("F1")
plt.xlabel("Fraction of comparisons")
plt.show()
plt.plot(df["Fraction"],df['Time'])
plt.ylabel("Computing time per bootstrap")
plt.xlabel("Fraction of comparisons")
plt.show()

plt.plot(df["Time"],df['F1'])
plt.xlabel("Computing time per bootstrap")
plt.ylabel("F1")
plt.show()